# Generated by Django 4.1.7 on 2023-03-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_profile_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(upload_to='product_image'),
        ),
    ]
