# Generated by Django 4.1.7 on 2023-03-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_product_color_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ram',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='rom',
            field=models.IntegerField(max_length=50),
        ),
    ]
