# Generated by Django 4.1.7 on 2023-03-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_description_alter_product_ram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='orginalprice',
            field=models.IntegerField(null=True),
        ),
    ]
