# Generated by Django 5.0.3 on 2024-03-27 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_orginalprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ram',
            new_name='size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rom',
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
