# Generated by Django 4.1.7 on 2023-03-25 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_cart_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
