# Generated by Django 4.1.7 on 2023-03-25 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_profile_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0011_delete_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('productname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_product', to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'productname')},
            },
        ),
    ]
