# Generated by Django 4.1.7 on 2023-03-26 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentdetails',
            name='totalprice',
        ),
    ]
