# Generated by Django 4.1.7 on 2023-03-26 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_remove_paymentdetails_totalprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='ifsc',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
