# Generated by Django 4.1.7 on 2023-03-26 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_profile_status'),
        ('customer', '0015_remove_payment_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p_payment', to='store.product'),
        ),
    ]
