# Generated by Django 4.1.7 on 2023-03-26 21:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_profile_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0016_payment_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Paymentdetails',
            new_name='Purchasedetails',
        ),
    ]
