# Generated by Django 4.1.7 on 2023-03-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_rename_productname_cart_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Purchasedetails',
        ),
    ]
