# Generated by Django 4.1.7 on 2023-03-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0019_payment_quantity_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='quantity',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
